# Mike Ezane is building a basic EC2 instance in a default VPC in  us-west-1 region 
# with a key pair use using the CLI
Description: >
  "Using CLI to provision my second basic EC2 instance with a default VPC in us-west-1 region with a hard coded 
  value for the AZ us-west-1b" and using a key pair.
Resources:
  HomeworkEC2InstanceForMikeEzane:
    Type:  AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-017c001a88dd93847"
      AvailabilityZone: "us-west-1b"
      
      Tags: 
        - Key: "Name"
          Value: "MikeFirstEC2"
        - Key: "Department"
          Value: "Finance"  
      KeyName: cfn-key1
  SGPing:
    Type: AWS::EC2::SecurityGroup
    Properties:
     GroupDescription: Enable SSH access via port 22 and 80
     SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 10.0.0.0/24