# Mike Ezane is building a basic EC2 instance in a default VPC in  us-west-1 region.
Description: >
  "This is my first basic EC2 instance deployed in a default VPC in us-west-1 region with a hard coded 
  value for the AZ us-west-1b"
Resources:
  HomeworkEC2InstanceForMikeEzane:
    Type:  AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-017c001a88dd93847"
      AvailabilityZone: "us-west-1b"
      Tags: 
        - Key: "Name"
          Value: "MikeFirstEC2"
        - Key: "Department"
          Value: "Finance"  


