AWSTemplateFormatVersion: 2010-09-09
Description: AZ Parameter demo

Parameters:
  MikeKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName
    Default: 'Serv22'
  MikeAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: us-west-1b
    AllowedValues:
      - us-west-1b
      - us-west-1c    
      
  MikeInstanceType:
    Description: Select the ec2 instance type from SSM
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/ec2/instancetype
  ImageId:
    Description: select the ec2 image from SSM
    # Type: AWS::SSM::Parameter::Value<String>
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::ID>
    # Default: MikePara
    # Default: /aws/service/ami-amazon-wondow-latest/
    Default: /aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base

Resources: 
  MikeEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref MikeInstanceType
      KeyName: !Ref MikeKeyName
      SecurityGroups:
        - default        
        - !Ref MikeSSHSecurityGroup 
      AvailabilityZone: !Ref MikeAvailabilityZone      
  MikeSSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0




